#select timestamp(now());
#select curdate();
#select curtime();
#select now();
#select date(now());
#select day(now());
#select dayname(now());
#select dayofweek(now());
#select ceil(7);
#select floor(2);
#select 2 mod 1;
#select pi();
#select pow(2,2);
#select rand();
#select round(2);
#select sqrt(49);
#select 10 div 2;
#use lab;
#alter table users add column Post_time datetime default current_timestamp;
#select* from users;
#update users set Settings = 'NULL' where id = 6;
#set sql_safe_updates = 1;